default:
  api:
    market_ticker: RATECUTCOUNT-24DEC31-T4
    trade_side: "yes"
  market_maker:
    max_position: 10
    order_expiration: 18000
    gamma: 0.1
    k: 1.5
    sigma: 0.001
    T: 18000 # 5 hours
    min_spread: 0.0
    position_limit_buffer: 0.1
    inventory_skew_factor: 0.001
  dt: 1.0
