real_simple:
  api:
    type: real
    market_ticker: FEDDECISION-24NOV-C26
    trade_side: yes
  market_maker:
    type: simple
    spread: 0.10
    max_position: 10
    order_expiration: 60
  log_level: INFO
  dt: 3.0

real_avellaneda:
  api:
    type: real
    market_ticker: FEDDECISION-24NOV-C26
    trade_side: yes
  market_maker:
    type: avellaneda
    max_position: 10
    order_expiration: 60
    gamma: 0.7
    k: 1.5
    sigma: 0.00001
    T: 3600
  log_level: INFO
  dt: 4.0

simulated_avellaneda:
  api:
    type: simulated
    initial_price: 0.5
    volatility: 0.00001
  market_maker:
    type: avellaneda
    max_position: 10
    order_expiration: 60
    gamma: 0.5
    k: 1.2
    sigma: 0.00002
    T: 7200
  log_level: INFO
  dt: 0.01

simulated_simple:
  api:
    type: simulated
    initial_price: 0.5
    volatility: 0.00001
  market_maker:
    type: simple
    spread: 0.10
    max_position: 10
    order_expiration: 60
  log_level: INFO
  dt: 0.1